pref("extensions.{77485BDA-6FFE-5A73-B3ED-943F929C15AE}.description", "chrome://grabit/locale/grabit.properties");
pref("extensions.grabit.Downloader_4_X.quiet", false);
pref("extensions.grabit.GetRight.autostart", false);
pref("extensions.grabit.GetRight.old", false);
pref("extensions.grabit.GetRight.quick", true);
pref("extensions.grabit.GetRight.replaceSpecialChars", true);
pref("extensions.grabit.LeechGet.httpLog", false);
pref("extensions.grabit.altClick", true);
pref("extensions.grabit.gesture", true);
pref("extensions.grabit.gesture.feedback", true);
pref("extensions.grabit.autoReferrer", true);
pref("extensions.grabit.autoStart", true);
pref("extensions.grabit.bgProcessing", true);
pref("extensions.grabit.bypassCombo", true);
pref("extensions.grabit.detect.auto", true);
pref("extensions.grabit.extfilter", false);
pref("extensions.grabit.fakeReferrer", "");
pref("extensions.grabit.hide-autotest", true);
pref("extensions.grabit.hide-icons", false);
pref("extensions.grabit.hide-tabs", true);
pref("extensions.grabit.hideDisabledCmds", true);
pref("extensions.grabit.hideToolsMenu", false);
pref("extensions.grabit.httpauth", false);
pref("extensions.grabit.includeImages", false);
pref("extensions.grabit.interceptAll", false);
pref("extensions.grabit.logEnabled", true);
pref("extensions.grabit.metalink", true);
pref("extensions.grabit.multiQuiet", false);
pref("extensions.grabit.nested-menu", false);
pref("extensions.grabit.omitCookies", false);
pref("extensions.grabit.rsPremium", false);
pref("extensions.grabit.selection.guessPassword", true);
pref("extensions.grabit.redir.anonymous.anonym_to", true);
pref("extensions.grabit.redir.anonymous.anonymz_com", true);
pref("extensions.grabit.redir.anonymous.stealth_to", true);
pref("extensions.grabit.redir.anonymous.sf_net", true);
pref("extensions.grabit.redir.generic.rx", "^https?://(?!web\\.archive\\.org/web/\\d+).*?(\\bhttps?(?::|%3A)(?:%2F|/)+\\w+[^&]*)");
pref("extensions.grabit.redir.generic.exceptions", "");
pref("extensions.grabit.redir.megaupload_com.force", false);
pref("extensions.grabit.redir.generic.enabled", true);
pref("extensions.grabit.redir.rapidshare_com.enabled", true);
pref("extensions.grabit.redir.filesonic_com.enabled", false);

pref("extensions.grabit.appleScriptEncoding", "UTF-8");
pref("extensions.grabit.queryStringSuffix", "");
pref("extensions.grabit.useWine", false);
pref("extensions.grabit.wine.paths", "/usr/bin/wine:/usr/local/bin/wine:/opt/local/bin/wine:/Applications/Darwine/Wine.bundle/Contents/bin/wine");
pref("extensions.grabit.oldSD", false);
pref("extensions.grabit.noDesc", false);

pref("extensions.grabit.media.guessName", true);
pref("extensions.grabit.media.use_iframe_title", false);
pref("extensions.grabit.media.forceNameHack", false);
pref("extensions.grabit.media.statusIcon", true);
pref("extensions.grabit.media.unicode", true);
pref("extensions.grabit.media.enabled", true);
pref("extensions.grabit.media.redirect", 1);
pref("extensions.grabit.media.redirect.joost_com", 0);
pref("extensions.grabit.media.minSize.flv", 500000);
pref("extensions.grabit.media.iconInstalled", false);
pref("extensions.grabit.media.skipAds", true);
pref("extensions.grabit.media.YouTube.autodetect", true);
pref("extensions.grabit.media.YouTube.seek_pos.show", true);
pref("extensions.grabit.media.YouTube.seek_pos.show_ms", false);
pref("extensions.grabit.media.YouTube.seek_pos.compact", true);
pref("extensions.grabit.media.YouTube.flashvars_element_id", "movie_player");
pref("extensions.grabit.media.YouTube.flashvars_element_attr", "flashvars");
pref("extensions.grabit.media.YouTube.decode_signature_func.sandbox", true);
pref("extensions.grabit.media.YouTube.decode_signature_func.auto", true);
pref("extensions.grabit.media.YouTube.stream_url.tidy", false);
pref("extensions.grabit.media.YouTube.stream_url.extra_keep_params", "");
pref("extensions.grabit.media.YouTube.remap_stream_quality", false);
pref("extensions.grabit.media.YouTube.remap_stream_type", false);
pref("extensions.grabit.media.autoCloseDocument", false);
pref("extensions.grabit.media.YouTube.type_sort_order", "video/mp4, video/x-flv, video/webm, video/3gpp, audio/mp4, audio/webm");
pref("extensions.grabit.media.YouTube.remap_type_sort_order", "mp4, flv, webm, 3gp, audio/mp4, audio/webm");
pref("extensions.grabit.media.YouTube.itag_map.quality_sort_key.480", "480");
pref("extensions.grabit.media.YouTube.itag_map.quality_sort_key.480.itags", "59");



pref("extensions.grabit.dmsopts._Built_In_.redir.filesonic_com.enabled", false);
pref("extensions.grabit.dmsopts._Built_In_.invertAltShiftClick", false);
pref("extensions.grabit.dmsopts._Built_In_.overwrite", false);
pref("extensions.grabit.dmsopts._Built_In_.showDM", true);
pref("extensions.grabit.dmsopts._Built_In_.noRedir", false);
pref("extensions.grabit.dmsopts._Built_In_.noRedir.extensions", "\\.(?:gif|jpe?g|png|svg|avi|asf|flv|mov|mp(?:e?g|[34])|wmv|ogg|mk[va]|au|wav|7z|bz2?|gz(?:ip)?|rar|tar|zip|cbr|cbz|exe|msi|iso|dmg|torrent|\\d{3})$");
pref("extensions.grabit.dmsopts.Net_Transport.encode", false);
pref("extensions.grabit.dmsopts.Net_Transport_2.stripHash", true);
pref("extensions.grabit.dmsopts.FlashGet.asciiFilter", true);
pref("extensions.grabit.dmsopts.FlashGet.cookiePersistence", 24);

pref("extensions.grabit.dmsopts.JDownloader.url", "http://127.0.0.1:9666/flashgot");
pref("extensions.grabit.dmsopts.JDownloader.delay", 8);
pref("extensions.grabit.dmsopts.JDownloader.autostart", true);
pref("extensions.grabit.dmsopts.JDownloader.quiet", false);

pref("extensions.grabit.dmsopts.pyLoad.url", "http://127.0.0.1:9666/flashgot");
pref("extensions.grabit.dmsopts.pyLoad.autostart", true);

pref("extensions.grabit.java", "");
pref("extensions.grabit.shredding", false);
pref("extensions.grabit.term.autoClose", -1);